# Generated by Django 5.2 on 2025-04-26 21:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessamentoAleatorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_selecao', models.IntegerField(choices=[(1, 'Tipo 1'), (2, 'Tipo 2'), (3, 'Tipo 3'), (4, 'Tipo 4')])),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('falha', 'Falha')], default='pendente', max_length=20)),
                ('dados_entrada', models.JSONField(blank=True, default=dict)),
                ('resultado', models.JSONField(blank=True, null=True)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
                ('progresso', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
