# Generated by Django 5.2 on 2025-04-26 21:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessamentoRPA',
            fields=[
                ('tipo', models.CharField(choices=[('planilha', 'Processamento de Planilha'), ('email', 'Automação de Email'), ('web', 'Automação Web'), ('sistema', 'Interação com Sistema')], max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('tempo_estimado', models.IntegerField(default=60, help_text='Tempo estimado em segundos')),
                ('tempo_real', models.IntegerField(blank=True, help_text='Tempo real em segundos', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_selecao', models.IntegerField(choices=[(1, 'Tipo 1'), (2, 'Tipo 2'), (3, 'Tipo 3'), (4, 'Tipo 4')])),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('falha', 'Falha')], default='pendente', max_length=20)),
                ('dados_entrada', models.JSONField(blank=True, default=dict)),
                ('resultado', models.JSONField(blank=True, null=True)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
                ('progresso', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Processamento RPA',
                'verbose_name_plural': 'Processamentos RPA',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.DeleteModel(
            name='ProcessamentoAleatorio',
        ),
    ]
