# Generated by Django 5.2 on 2025-04-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_processamentorpa_delete_processamentoaleatorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processamentorpa',
            name='tipo_selecao',
        ),
        migrations.AlterField(
            model_name='processamentorpa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('falha', 'Falha')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='processamentorpa',
            name='tipo',
            field=models.CharField(choices=[('planilha', 'Processamento de Planilha'), ('email', 'Automação de Email'), ('web', 'Automação Web'), ('sistema', 'Interação com Sistema')], db_index=True, max_length=20),
        ),
    ]
