# Generated by Django 5.2 on 2025-04-27 00:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_processamentorpa_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessamentoRPATemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('planilha', 'Processamento de Planilha'), ('email', 'Automação de Email'), ('web', 'Automação Web'), ('sistema', 'Interação com Sistema')], db_index=True, max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('dados_entrada_template', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Template de Processamento RPA',
                'verbose_name_plural': 'Templates de Processamento RPA',
            },
        ),
        migrations.AlterField(
            model_name='processamentorpa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processamentorpa',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processamentos', to='core.processamentorpatemplate'),
        ),
    ]
