# Generated by Django 5.2 on 2025-04-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_processamentorpatemplate_alter_processamentorpa_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamentorpa',
            name='tipo',
            field=models.CharField(choices=[('planilha', 'Processamento de Planilha'), ('email', 'Automação de Email'), ('web', 'Automação Web'), ('sistema', 'Interação com Sistema'), ('docker_rpa', 'Processamento Docker RPA')], db_index=True, max_length=20),
        ),
    ]
