# Generated by Django 5.2 on 2025-05-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_processamentorpa_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('arquivo', models.FileField(upload_to='resultados/%Y/%m/%d/')),
            ],
        ),
    ]
