# Generated by Django 5.2 on 2025-05-02 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_resultado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processamentorpa',
            name='s3_directory',
            field=models.CharField(blank=True, help_text='Diretório S3 para este processamento', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processamentorpa',
            name='tipo',
            field=models.CharField(choices=[('planilha', 'Processamento de Planilha'), ('email', 'Automação de Email'), ('web', 'Automação Web'), ('sistema', 'Interação com Sistema'), ('docker_rpa', 'Processamento Docker RPA'), ('selecao_aleatoria', 'Seleção Aleatória')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='processamentorpa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processamentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ResultadoProcessamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('caminho_s3', models.CharField(blank=True, max_length=500, null=True)),
                ('arquivo_local', models.FileField(blank=True, null=True, upload_to='resultados/processamentos/%Y/%m/%d/')),
                ('tipo_resultado', models.CharField(choices=[('arquivo_excel', 'Arquivo Excel'), ('arquivo_pdf', 'Arquivo PDF'), ('arquivo_csv', 'Arquivo CSV'), ('imagem', 'Imagem'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tamanho_bytes', models.BigIntegerField(blank=True, default=0, null=True)),
                ('processamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_associados', to='core.processamentorpa')),
            ],
            options={
                'verbose_name': 'Resultado de Processamento',
                'verbose_name_plural': 'Resultados de Processamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
